version: '3.1'

services:
  postgresql:
    container_name: postgresql
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - postgresql-database:/var/lib/postgresql/data

volumes:
  postgresql-database:
    driver: local
